# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70fb5de7b9864b2b5a2d351a90435aedfa4e679c7c023d27cd4ba10c9a608b24f4f69d5430fd14533da287b5e1ab69cf4faa44927d72b1723e728ad0093304b2

test:
  secret_key_base: 95fda95fcdca0929c024a73b5d8a35597bc6c89867c790f61eb138b1a9900ff7fcb0f43d2cf03e81f36e4d4149f360d89deaad1590e3ff89db453caaa98441bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
